[programs.localnet]
sig_verify = "GTRqnYcgFdKRWrBA8eujeVN7kWfNgdQX1XH77SPfqoya"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/ppoliani/.config/solana/id.json"

[scripts]
test = "yarn run mocha -p -t 1000000 tests/**/*.js -- --experimental-json-modules"
