[programs.localnet]
basic_2 = "2NKe7BxFyyP5SL84e4n7sjQfGEGVyK9De1eGBr3uLs8N"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/ppoliani/.config/solana/id.json"

[scripts]
test = "yarn run mocha -p -t 1000000 tests/**/*.js -- --experimental-json-modules"
