[programs.localnet]
pupper = ""
pupper-master = ""

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/ppoliani/.config/solana/id.json"

[scripts]
test = "yarn run mocha -p -t 1000000 tests/**/*.js -- --experimental-json-modules"
